export const OMNI_CHAINS = [
    { id: 'world',      name: 'World',       color: '#000000', type: 'EVM' },
    { id: 'optimism',   name: 'Optimism',    color: '#FF0420', type: 'L2' },
    { id: 'ethereum',   name: 'Ethereum',    color: '#627EEA', type: 'L1' },
    { id: 'bitcoin',    name: 'Bitcoin',     color: '#F7931A', type: 'L1' },
    { id: 'solana',     name: 'Solana',      color: '#14F195', type: 'L1' },
    { id: 'bnb',        name: 'BNB Chain',   color: '#F3BA2F', type: 'L1' },
    { id: 'polygon',    name: 'Polygon',     color: '#8247E5', type: 'L2' },
    { id: 'arbitrum',   name: 'Arbitrum',    color: '#28A0F0', type: 'L2' },
    { id: 'base',       name: 'Base',        color: '#0052FF', type: 'L2' },
    { id: 'bttc',       name: 'BTTC',        color: '#123456', type: 'EVM' },
    { id: 'celo',       name: 'Celo',        color: '#35D07F', type: 'L1' },
    { id: 'gnosis',     name: 'Gnosis',      color: '#04795B', type: 'L1' },
    { id: 'linea',      name: 'Linea',       color: '#121212', type: 'L2' },
    { id: 'moonbeam',   name: 'Moonbeam',    color: '#53CBC9', type: 'L1' },
    { id: 'moonriver',  name: 'Moonriver',   color: '#E1147B', type: 'L1' },
    { id: 'scroll',     name: 'Scroll',      color: '#FFDAB9', type: 'L2' },
    { id: 'avax',       name: 'Avax C-Chain',color: '#E84142', type: 'L1' },
    { id: 'opbnb',      name: 'opBNB',       color: '#F3BA2F', type: 'L2' },
    { id: 'fraxtal',    name: 'Fraxtal',     color: '#000000', type: 'L2' },
    { id: 'blast',      name: 'Blast',       color: '#FCFC03', type: 'L2' },
    { id: 'mantle',     name: 'Mantle',      color: '#000000', type: 'L2' },
    { id: 'taiko',      name: 'Taiko',       color: '#E81899', type: 'L2' },
    { id: 'xdc',        name: 'XDC',         color: '#2175D9', type: 'L1' },
    { id: 'ape',        name: 'Ape',         color: '#0052FF', type: 'EVM' },
    { id: 'unichain',   name: 'Unichain',    color: '#FF007A', type: 'L2' },
    { id: 'berachain',  name: 'Berachain',   color: '#8D5A32', type: 'L1' },
    { id: 'memecore',   name: 'MemeCore',    color: '#00FF00', type: 'EVM' },
    { id: 'sonic',      name: 'Sonic',       color: '#121212', type: 'L1' },
    { id: 'abstract',   name: 'Abstract',    color: '#000000', type: 'L2' },
    { id: 'hyperevm',   name: 'HyperEVM',    color: '#6A0DAD', type: 'EVM' },
    { id: 'katana',     name: 'Katana',      color: '#E53935', type: 'EVM' },
    { id: 'sei',        name: 'Sei',         color: '#BF360C', type: 'L1' },
    { id: 'monad',      name: 'Monad',       color: '#8338EC', type: 'L1' },
    { id: 'plasma',     name: 'Plasma',      color: '#00D1FF', type: 'L2' },
    { id: 'stable',     name: 'Stable',     color: '#10B981', type: 'EVM' },
];
