export const API_MARKETPLACE_PLANS = [
  {
    id: "standard",
    name: "Standard",
    price: 15,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_STANDARD_PRICE || "price_standard",
    badge: "VALUED",
    description: "Ideal for novice traders. 3 main crypto assets.",
    color: "#050505",
    icon: "Activity",
    requests: "5,000 req/day",
    tokens: "3 tokens (BTC, ETH, BNB)",
    keys: "1 API key",
    features: [
      "REST API",
      "12h event window",
      "$1M threshold",
      "Basic support",
      "SLA 99.0%",
    ],
    sessionQualityBenefits: [
      "Faster data refresh rates",
      "Reduced latency on whale alerts",
      "Priority queue for API requests",
      "Extended session timeout (24h)",
    ],
  },
  {
    id: "starter",
    name: "Starter",
    price: 49,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_STARTER_PRICE || "price_starter",
    badge: null,
    description: "For independent traders and researchers.",
    color: "#050505",
    icon: "User",
    requests: "10,000 req/day",
    tokens: "5 tokens (BTC, ETH, BNB, SOL, XRP)",
    keys: "1 API key",
    features: [
      "REST API",
      "24h event window",
      "$500K threshold",
      "Email support",
      "SLA 99.5%",
    ],
    sessionQualityBenefits: [
      "Real-time WebSocket streams",
      "Lower API response times",
      "Enhanced session reliability",
      "Dedicated support channel",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: 299,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRO_PRICE || "price_pro",
    badge: "MOST POPULAR",
    description: "For professional desks and quants. Everything unlocked.",
    color: "#050505",
    icon: "Star",
    requests: "500,000 req/day",
    tokens: "24 tokens (Full suite)",
    keys: "3 API keys",
    features: [
      "REST + WebSocket + Webhooks",
      "30-day history",
      "$100K threshold",
      "Heikin-Ashi signals",
      "Tagged Elite wallets",
      "Dark pool detection",
      "Priority support + Telegram",
      "SLA 99.9%",
    ],
    sessionQualityBenefits: [
      "Ultra-low latency connections",
      "Unlimited session duration",
      "Advanced analytics dashboard",
      "Custom webhook integrations",
      "Priority infrastructure access",
    ],
  },
  {
    id: "Elite",
    name: "Elite",
    price: 1999,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_INST_PRICE || "price_Elite",
    badge: "MAXIMUM POWER",
    description: "For hedge funds, market makers and trading firms.",
    color: "#050505",
    icon: "Building2",
    requests: "Unlimited",
    tokens: "All + custom tokens",
    keys: "10 keys + sub-accounts",
    features: [
      "REST + WebSocket + FIX Protocol",
      "12-month history",
      "Customizable $50K threshold",
      "IP whitelist + HMAC signature",
      "CSV / Parquet exports",
      "Advanced anomaly detection",
      "Dedicated Slack + onboarding call",
      "SLA 99.99% dedicated infrastructure",
    ],
    sessionQualityBenefits: [
      "Dedicated server instances",
      "Custom session configurations",
      "Direct API team access",
      "On-premise deployment options",
      "Enterprise-grade SLA guarantees",
    ],
  },
];

export const SESSION_QUALITY_BENEFITS = {
  standard: [
    "Faster data refresh rates",
    "Reduced latency on whale alerts",
    "Priority queue for API requests",
    "Extended session timeout (24h)",
  ],
  starter: [
    "Real-time WebSocket streams",
    "Lower API response times",
    "Enhanced session reliability",
    "Dedicated support channel",
  ],
  pro: [
    "Ultra-low latency connections",
    "Unlimited session duration",
    "Advanced analytics dashboard",
    "Custom webhook integrations",
    "Priority infrastructure access",
  ],
  elite: [
    "Dedicated server instances",
    "Custom session configurations",
    "Direct API team access",
    "On-premise deployment options",
    "Enterprise-grade SLA guarantees",
  ],
};
