export interface FeatureContent {
  id: string;
  category: 'core' | 'trading' | 'productos' | 'developer' | 'about';
  title: string;
  subtitle: string;
  shortDesc: string;
  deepDive: string[];
  humanEdge: string;
  lottieSrc: string;
  lottieDescription: string;
  cta?: {
    text: string;
    link: string;
  };
}

export const ecosystemFeatures: FeatureContent[] = [
  // CORE ECOSYSTEM
  {
    id: 'wallet',
    category: 'core',
    title: 'Get Wallet',
    subtitle: 'Protocol: ERC-4337 Account Abstraction Layer',
    shortDesc: 'The end of the seed phrase era',
    deepDive: [
      'Traditional accounts (EOAs) are slaves to a private key. If you lose the key, you lose access. Whale Alert breaks this paradigm through Account Abstraction. Your wallet is not just an address, it\'s an intelligent Smart Contract deployed on the network.',
      'This allows us to implement Paymaster logic, meaning you can pay gas in any token (or we can subsidize it for you), eliminating the friction of having to buy ETH or MATIC to move your funds.',
      'Security is managed through a Multi-faceted Signature scheme, enabling social recovery: if you lose your device, your "Guardians" (trusted friends or secondary devices) can rotate your access key without your funds moving.',
      'We use elliptic curve cryptography y² = x³ + 7 over secp256k1, but abstracted for humans. We don\'t generate a vulnerable local private key; we deploy a Smart Contract Wallet with daily spending limits and social recovery.'
    ],
    humanEdge: 'Honestly, asking your grandmother to save 12 words on paper is an insult to 2026 software engineering. We are #1 because we\'ve killed the "Seed Phrase". We offer a Web2 banking experience with Web3 mathematical security. We\'re not "simplifying" blockchain; we\'re rebuilding it correctly.',
    lottieSrc: 'https://lottie.host/d5c4e8f5-8f3a-4c8e-9b5e-2f8c9d3e4f5a/6K7L8M9N0P.json',
    lottieDescription: 'An old metal key that melts and transforms into an interconnected network of nodes forming a digital fingerprint',
    cta: {
      text: 'View contract on Etherscan',
      link: '#'
    }
  },
  {
    id: 'predecir',
    category: 'core',
    title: 'Predict',
    subtitle: 'Low Latency Prediction Markets',
    shortDesc: 'Sub-second oracles, unbiased mathematics',
    deepDive: [
      'We use a Constant Product Market Maker (CPMM) model optimized for binary events. Our pricing accuracy is based on the formula: P_a = R_b / (R_a + R_b), where R_a and R_b are the reserves of the possible outcomes.',
      'Thanks to our low-latency oracles integrated directly into the execution layer, we reduce toxic arbitrage by 94% compared to competitors.',
      'Honesty here is key: most prediction markets are slow and manipulatable. Ours is mathematically unbiased.',
      'We don\'t bet against you; we facilitate statistical truth through Gnosis CPMM, Chainlink/UMA integration, and transparent market resolution.'
    ],
    humanEdge: 'We are #1 because we have sub-second oracle updates vs the 5 minute lag of Polymarket. Speed is not luxury, it\'s justice in prediction markets.',
    lottieSrc: 'https://lottie.host/embed/a1b2c3d4-e5f6-7g8h-9i0j-k1l2m3n4o5p6/qrstuvwxyz.json',
    lottieDescription: 'Crystal ball with probability waves stabilizing into a clear outcome'
  },
  {
    id: 'comprar-ganar',
    category: 'core',
    title: 'Buy / Earn / Redeem',
    subtitle: 'Aggregated Liquidity & Yield Farming',
    shortDesc: '0.1% fees with integrated MEV protection',
    deepDive: [
      'We implement aggregated liquidity pools with slippage protection. Our engine analyzes multiple DEXs simultaneously to ensure the best execution price.',
      'Yield farming is managed through audited low-risk strategies, with transparent APYs calculated in real-time.',
      'Integrated MEV (Maximal Extractable Value) protection in every swap to prevent sandwich attacks and front-running.',
      'Competitive 0.1% fees vs 0.5% on Binance, with rewards distributed to governance token holders.'
    ],
    humanEdge: 'While other exchanges charge you hidden fees in the spread, we show the real cost of every operation. Transparency is our competitive advantage.',
    lottieSrc: 'https://lottie.host/embed/b2c3d4e5-f6g7-8h9i-0j1k-l2m3n4o5p6q7/rstuvwxyz.json',
    lottieDescription: 'Liquidity flow through interconnected nodes with glow effect'
  },
  {
    id: 'recompensas',
    category: 'core',
    title: 'Rewards',
    subtitle: 'Fee Distribution to Holders',
    shortDesc: 'Transparent staking with real APY',
    deepDive: [
      'Automatic distribution system of protocol fees to holders who stake HUMAN tokens.',
      'Real-time reward calculation based on your share of the total pool.',
      'No mandatory lock-ups: you can withdraw your tokens at any time.',
      'Full transparency: every fee generated by the protocol is traceable on-chain.'
    ],
    humanEdge: 'We don\'t promise fanciful 10000% APYs. We show real returns based on protocol activity. Honesty generates long-term trust.',
    lottieSrc: 'https://lottie.host/embed/c3d4e5f6-g7h8-9i0j-1k2l-m3n4o5p6q7r8/stuvwxyz.json',
    lottieDescription: 'Coins falling into a vault with reward counter'
  },

  // TRADING & SECURITY
  {
    id: 'perps',
    category: 'trading',
    title: 'Perps (Perpetuals)',
    subtitle: 'Execution Engine: High-Frequency On-Chain Settlement',
    shortDesc: '100x leverage without house advantage',
    deepDive: [
      'Trading perpetuals on centralized exchanges is often a rigged game: the exchange sees your stop-losses and trades against you. At Whale Alert, the matching engine is a hybrid architecture: order taking is instantaneous (off-chain) but settlement and funds custody is on-chain.',
      'We calculate the Funding Rate every second to ensure the perpetual contract price follows the spot price without malicious deviations: Funding = max(0.01%, Premium) + min(0, Premium)',
      'Our liquidations engine is a public smart contract. There is no "secret liquidator" taking your funds; there is a Community Insurance Fund that guarantees protocol solvency even in "Black Swan" events.',
      'Up to 100x leverage with transparent risk management and fair liquidations.'
    ],
    humanEdge: 'Professional traders are fed up with exchanges going down right when there is volatility. We are #1 because our engine has no "off" button. We are not your counterparty; we are the impartial referee.',
    lottieSrc: 'https://lottie.host/embed/d4e5f6g7-h8i9-0j1k-2l3m-n4o5p6q7r8s9/tuvwxyz.json',
    lottieDescription: 'Trading candles transforming into blockchain blocks with security locks'
  },
  {
    id: 'escudo',
    category: 'trading',
    title: 'Transaction Shield',
    subtitle: 'Security Terminal: HumanShield_v2.0.bin',
    shortDesc: 'We stop the attack before it hits the chain',
    deepDive: [
      'The big failure of today\'s Web3 is "Blind Signing". When you sign in MetaMask, you are authorizing a state change in the EVM without understanding the consequences. The Transaction Shield acts as an interception layer at the RPC level.',
      'Before requesting your signature, our engine runs a Deterministic State Validation. If the target contract contains reentrancy logic, honeypot, or if the impact on your balance does not match the operation intent, the system generates a security exception.',
      'We use a risk analysis model based on: R = Σ(Vi × Pi), where V is the vulnerability detected in the bytecode and P is the severity weight.',
      'MEV protection, honeypot detection, real-time contract analysis, and pre-flight validation for every transaction.'
    ],
    humanEdge: 'The competition gives you a 50-page manual on how not to be scammed. We have coded that manual into the wallet core. We turn security from a user responsibility into a system guarantee.',
    lottieSrc: 'https://lottie.host/embed/e5f6g7h8-i9j0-1k2l-3m4n-o5p6q7r8s9t0/uvwxyz.json',
    lottieDescription: 'Green laser scanning data blocks, hexagonal shield blocking red threats'
  },
  {
    id: 'snaps',
    category: 'trading',
    title: 'Snaps',
    subtitle: 'Total Modularity',
    shortDesc: 'Sandboxed extensions to customize your wallet',
    deepDive: [
      'Inspired by micro-kernel architectures, Snaps allow injecting custom logic into the wallet through an isolated execution environment (sandboxed).',
      'This allows external protocols to add security or visualization features without compromising the user\'s private keys.',
      'Open SDK vs the closed ecosystem of MetaMask.',
      'Permissioned APIs with granular control over what each extension can do.'
    ],
    humanEdge: 'We are #1 because we open our platform to innovation without sacrificing security. Open SDK, sandboxed execution, zero-trust architecture.',
    lottieSrc: 'https://lottie.host/embed/f6g7h8i9-j0k1-2l3m-4n5o-p6q7r8s9t0u1/vwxyz.json',
    lottieDescription: 'Translucent puzzle pieces magnetically assembling'
  },

  // PRODUCTOS
  {
    id: 'tarjeta',
    category: 'productos',
    title: 'Whale Card',
    subtitle: 'Fiat-Crypto Bridge',
    shortDesc: '0% markup FX, instant conversion',
    deepDive: [
      'The Whale Card is not just plastic; it\'s a payment endpoint that resolves the off-ramp through an instant settlement protocol.',
      'Visa payment rail integration, KYC/AML compliance, real-time crypto→fiat conversion.',
      'Total fee transparency: 0% FX markup vs 2.99% on Crypto.com.',
      'Spend your cryptocurrencies at any merchant that accepts Visa, seamlessly.'
    ],
    humanEdge: 'While others charge you a hidden 3% "spread" in conversion, we show the real network cost. Honesty is our best retention metric.',
    lottieSrc: 'https://lottie.host/embed/g7h8i9j0-k1l2-3m4n-5o6p-q7r8s9t0u1v2/wxyz.json',
    lottieDescription: 'Credit card materializing from digital particles'
  },
  {
    id: 'husd',
    category: 'productos',
    title: 'Human USD (hUSD)',
    subtitle: 'Protocol: Stabilized Asset Minting (SAM)',
    shortDesc: 'Total transparency where others only offer promises',
    deepDive: [
      'Human USD (hUSD) is based on a Hybrid Over-collateralized model. Unlike purely algorithmic models that tend toward death spirals, hUSD maintains its parity through a basket of liquid assets and an incentivized arbitrage mechanism.',
      'System health coefficient: H = (Σ Collateral_i × Price_i) / Total_hUSD_Supply × 100. We maintain H > 150%.',
      'Integrated Chainlink Proof of Reserve (PoR): any user can verify in real-time that every hUSD has an equivalent physical or digital backing.',
      'If collateral value drops, the system triggers dynamic Stability Fees to incentivize hUSD burning and restore balance.'
    ],
    humanEdge: 'We eliminate "faith" from the financial system. While large stablecoins ask you to trust quarterly audits, we give you a per-block audit. It\'s the honesty of mathematics vs banking opacity.',
    lottieSrc: 'https://lottie.host/embed/h8i9j0k1-l2m3-4n5o-6p7q-r8s9t0u1v2w3/xyz.json',
    lottieDescription: 'Dollar symbol floating over scale with orbiting collateral spheres'
  },
  {
    id: 'smart-accounts',
    category: 'productos',
    title: 'Smart Accounts Kit',
    subtitle: 'Protocol: ERC-4337 Account Abstraction Layer',
    shortDesc: 'Human engineering for real digital sovereignty',
    deepDive: [
      'Your wallet is not just a simple address, it\'s an intelligent Smart Contract deployed on the network.',
      'Paymasters: pay gas in any token or we subsidize it.',
      'Social Recovery: your "Guardians" can rotate your access key without moving funds.',
      'Session Keys: authorize applications for a limited time without exposing your master key.',
      'Gasless transactions, programmable spending limits, and multi-signature security.'
    ],
    humanEdge: 'Asking someone to save 12 words on a piece of paper is an insult to 2026 engineering. We have killed the Seed Phrase. Web2 experience, Web3 security.',
    lottieSrc: 'https://lottie.host/embed/i9j0k1l2-m3n4-5o6p-7q8r-s9t0u1v2w3x4/yz.json',
    lottieDescription: 'Key transforming into digital fingerprint with guardian network'
  },

  // DEVELOPER HUB
  {
    id: 'docs',
    category: 'developer',
    title: 'Documentation',
    subtitle: 'Docs.human_defi.io / Technical Specification',
    shortDesc: 'No "coming soon", no broken links',
    deepDive: [
      'Our documentation is not a simple manual; it\'s a military-grade technical specification. Structured following the Diátaxis pattern: tutorials, conceptual guides, auto-generated API references.',
      'Every function of our Smart Contracts is documented with the NatSpec standard.',
      'We explain the attack vectors we consider in each audit and the invariants our contracts maintain.',
      'If you find an error in the docs, there is an automated reward.'
    ],
    humanEdge: 'Most Web3 projects hide their complexity behind bad documentation. We expose our guts. We want you to build on us, not fight against us.',
    lottieSrc: 'https://lottie.host/embed/k1l2m3n4-o5p6-7q8r-9s0t-u1v2w3x4y5z6/a.json',
    lottieDescription: 'Ancient book projecting 3D data city hologram'
  },

  // ABOUT
  {
    id: 'seguridad',
    category: 'about',
    title: 'Security',
    subtitle: 'Protocol: Continuous Defense & Formal Verification',
    shortDesc: 'Formal verification, not luck',
    deepDive: [
      'Security is not an annual PDF audit. We implement Continuous Security (SecOps) with Formal Verification: we mathematically prove the code behaves according to the specification.',
      'Property-Based Testing: thousands of random scenarios to break invariants.',
      'Time-locks & Multisig: critical changes require a 48h wait and validator quorum.',
      'Active $1M USD Bug Bounty. Audited by Trail of Bits.',
      'Circuit breakers: if a component is at risk, it is isolated until 100% secure.'
    ],
    humanEdge: 'We treat every line of code like a life support system. We prioritize State Resilience over Time-to-Market. We don\'t "fix in production".',
    lottieSrc: 'https://lottie.host/embed/n4o5p6q7-r8s9-0t1u-2v3w-x4y5z6a7b8c9/d.json',
    lottieDescription: 'Geodesic dome absorbing threats and emitting protection waves'
  },
  {
    id: 'support',
    category: 'about',
    title: 'Support',
    subtitle: 'Service: Human-to-Human Concierge',
    shortDesc: 'Because in critical moments, a bot is an insult',
    deepDive: [
      'We have eliminated FAQ mazes and automatic bots. Our support is composed of level 2 and 3 engineers who understand blockchain.',
      'If you have a problem, you speak to someone who knows how to read the block explorer.',
      'Integrated on-chain traceability tools: precise answers in minutes, not days.',
      '24/7 support with real humans.'
    ],
    humanEdge: 'Most exchanges are "ghosts": there is no one to claim to. We are #1 because we are here. Total transparency means accountability.',
    lottieSrc: 'https://lottie.host/embed/o5p6q7r8-s9t0-1u2v-3w4x-y5z6a7b8c9d0/e.json',
    lottieDescription: 'Beating organic heart built of code and gold circuits'
  }
];
