// Address Configuration for Type V Civilization Contracts
// Generated by Operation Genesis

export const CIVILIZATION_CONTRACTS = {
    MANA: "0xDB52e67A9EBD7Fd89baaF3C6D22caDa2a324310A" as `0x${string}`,
    MATTER: "0xA3E6960AbDe231f38cbed6BcAe0265Cd1Be2dB74" as `0x${string}`,
    CONSTITUTION: "0x4c6a0C48c557D5E197635bb7Dd53f11D3fc50702" as `0x${string}`,
    GOVERNANCE: "0xb8b861BeF1160a015d460484CADb046D62F33eA4" as `0x${string}`,
    ASCENSION: "0x10bC464831074ecE5d952d156BaCCf81652a42ef" as `0x${string}`,
} as const;

