/**
 * deploy-qd-live.mjs
 * ─────────────────────────────────────────────────────────────────────────────
 * Deploys QuantumDots (QDs) + QuantumLedger to Base Mainnet.
 *
 * Does NOT use the Hardhat runtime — runs as a plain Node ESM script with
 * ethers v6, bypassing the WASM compile error in the current environment.
 *
 * Usage:
 *   node scripts/deploy-qd-live.mjs
 *
 * Requirements:
 *   - PRIVATE_KEY set in .env (deployer wallet, must have ETH for gas)
 *   - BASE_MAINNET_RPC or GB_BASE_RPC_1 set in .env (Base Mainnet JSON-RPC)
 *
 * Output:
 *   Prints the two contract addresses. Copy them to .env as:
 *     NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS=<QuantumDots address>
 *     NEXT_PUBLIC_LEDGER_CONTRACT_ADDRESS=<QuantumLedger address>
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { ethers } from "ethers";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// ── Load .env manually (no dotenv dep required in ESM) ──────────────────────
function loadEnv() {
  const envPath = join(ROOT, ".env");
  const lines = readFileSync(envPath, "utf8").split("\n");
  const env = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    // Strip surrounding quotes
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    env[key] = val;
  }
  return env;
}

const env = loadEnv();

const RPC_URL =
  env.BASE_MAINNET_RPC ||
  env.BASE_MAINNET_RPC_URL ||
  env.GB_BASE_RPC_1 ||
  "https://mainnet.base.org";

const RAW_KEY = env.PRIVATE_KEY;
if (!RAW_KEY) {
  console.error("[ABORT] PRIVATE_KEY not found in .env");
  process.exit(1);
}
// Normalise: add 0x prefix if missing
const PRIVATE_KEY = RAW_KEY.startsWith("0x") ? RAW_KEY : `0x${RAW_KEY}`;

const SOVEREIGN_VAULT = "0x78831C25c86eA2a78A6127fC2Ccb95E612D87b4a";

// ── Minimal ABIs for deployment verification ────────────────────────────────
const QD_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function MAX_SUPPLY() view returns (uint256)",
  "function GENESIS_SUPPLY() view returns (uint256)",
  "function SOVEREIGN_VAULT() view returns (address)",
];

const LEDGER_ABI = [
  "function quantumDots() view returns (address)",
  "function totalReceipts() view returns (uint256)",
];

// ── Bytecodes (compiled output) ──────────────────────────────────────────────
// We embed the ABI + bytecode inline to avoid Hardhat artifacts dependency.
// These are generated by: npx hardhat compile
// If recompiling is needed, run: npx hardhat compile --force
let QD_BYTECODE, LEDGER_BYTECODE, QD_FULL_ABI, LEDGER_FULL_ABI;

try {
  const qdArtifact = JSON.parse(
    readFileSync(join(ROOT, "artifacts/contracts/quantum/QuantumDots.sol/QuantumDots.json"), "utf8")
  );
  const ledgerArtifact = JSON.parse(
    readFileSync(join(ROOT, "artifacts/contracts/quantum/QuantumLedger.sol/QuantumLedger.json"), "utf8")
  );
  QD_BYTECODE    = qdArtifact.bytecode;
  LEDGER_BYTECODE = ledgerArtifact.bytecode;
  QD_FULL_ABI    = qdArtifact.abi;
  LEDGER_FULL_ABI = ledgerArtifact.abi;
  console.log("[OK] Artifacts loaded from cache.");
} catch {
  console.error("[ABORT] Compiled artifacts not found.");
  console.error("       Run: npx hardhat compile");
  console.error("       Then re-run this script.");
  process.exit(1);
}

// ── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log("\n╔════════════════════════════════════════════════════════════╗");
  console.log("║  QuantumDots + QuantumLedger — Base Mainnet Deploy        ║");
  console.log("╚════════════════════════════════════════════════════════════╝\n");

  const provider = new ethers.JsonRpcProvider(RPC_URL);
  const wallet   = new ethers.Wallet(PRIVATE_KEY, provider);

  // ── Pre-flight checks ─────────────────────────────────────────────────────
  const [network, deployerBalance] = await Promise.all([
    provider.getNetwork(),
    provider.getBalance(wallet.address),
  ]);

  console.log(`  Network  : ${network.name} (chainId ${network.chainId})`);
  console.log(`  Deployer : ${wallet.address}`);
  console.log(`  Balance  : ${ethers.formatEther(deployerBalance)} ETH`);
  console.log(`  RPC      : ${RPC_URL}\n`);

  if (network.chainId !== 8453n) {
    console.error(`[ABORT] Expected Base Mainnet (8453), got chainId ${network.chainId}.`);
    process.exit(1);
  }

  if (deployerBalance === 0n) {
    console.error("[ABORT] Deployer has 0 ETH. Fund the wallet before deploying.");
    process.exit(1);
  }

  const minGasRequired = ethers.parseEther("0.0005"); // ~$1.50 at $3000/ETH
  if (deployerBalance < minGasRequired) {
    console.warn(`[WARN] Balance < 0.0005 ETH. Deployment may fail due to insufficient gas.`);
  }

  // ── Deploy QuantumDots ────────────────────────────────────────────────────
  console.log("  [1/4] Deploying QuantumDots (QDs)...");
  const qdFactory = new ethers.ContractFactory(QD_FULL_ABI, QD_BYTECODE, wallet);
  const qd = await qdFactory.deploy(wallet.address); // deployer = admin
  console.log(`        Tx hash  : ${qd.deploymentTransaction()?.hash}`);
  await qd.waitForDeployment();
  const qdAddress = await qd.getAddress();
  console.log(`        Address  : ${qdAddress} ✓\n`);

  // ── Verify genesis allocation ─────────────────────────────────────────────
  console.log("  [2/4] Verifying genesis allocation...");
  const qdView = new ethers.Contract(qdAddress, QD_ABI, provider);
  const [totalSupply, vaultBalance, maxSupply] = await Promise.all([
    qdView.totalSupply(),
    qdView.balanceOf(SOVEREIGN_VAULT),
    qdView.MAX_SUPPLY(),
  ]);

  console.log(`        MAX_SUPPLY      : ${ethers.formatEther(maxSupply)} QDs`);
  console.log(`        totalSupply     : ${ethers.formatEther(totalSupply)} QDs`);
  console.log(`        Sovereign Vault : ${ethers.formatEther(vaultBalance)} QDs`);

  if (vaultBalance !== 5_000_000n * 10n ** 18n) {
    console.error("[ABORT] Genesis allocation mismatch. Expected 5,000,000 QDs in Sovereign Vault.");
    process.exit(1);
  }
  console.log("        Genesis allocation: 5,000,000 QDs confirmed ✓\n");

  // ── Deploy QuantumLedger ──────────────────────────────────────────────────
  console.log("  [3/4] Deploying QuantumLedger v2...");
  const ledgerFactory = new ethers.ContractFactory(LEDGER_FULL_ABI, LEDGER_BYTECODE, wallet);
  const ledger = await ledgerFactory.deploy(qdAddress);
  console.log(`        Tx hash  : ${ledger.deploymentTransaction()?.hash}`);
  await ledger.waitForDeployment();
  const ledgerAddress = await ledger.getAddress();
  console.log(`        Address  : ${ledgerAddress} ✓\n`);

  // ── Verify QuantumLedger ──────────────────────────────────────────────────
  console.log("  [4/4] Verifying QuantumLedger configuration...");
  const ledgerView = new ethers.Contract(ledgerAddress, LEDGER_ABI, provider);
  const linkedToken = await ledgerView.quantumDots();
  if (linkedToken.toLowerCase() !== qdAddress.toLowerCase()) {
    console.error("[ABORT] QuantumLedger linked to wrong token address!");
    process.exit(1);
  }
  console.log(`        Linked token: ${linkedToken} ✓`);
  console.log("        QuantumLedger v2 ready to process transfers ✓\n");

  // ── Final output ──────────────────────────────────────────────────────────
  console.log("╔════════════════════════════════════════════════════════════╗");
  console.log("║  DEPLOYMENT COMPLETE                                       ║");
  console.log("╠════════════════════════════════════════════════════════════╣");
  console.log(`║  QuantumDots  : ${qdAddress}`);
  console.log(`║  QuantumLedger: ${ledgerAddress}`);
  console.log("╠════════════════════════════════════════════════════════════╣");
  console.log("║  Add these to Railway + .env:                              ║");
  console.log(`║  NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS=${qdAddress}`);
  console.log(`║  NEXT_PUBLIC_LEDGER_CONTRACT_ADDRESS=${ledgerAddress}`);
  console.log(`║  NEXT_PUBLIC_CHAIN_ID=8453`);
  console.log("╚════════════════════════════════════════════════════════════╝\n");

  console.log(`  Verify on BaseScan:`);
  console.log(`  https://basescan.org/address/${qdAddress}`);
  console.log(`  https://basescan.org/address/${ledgerAddress}`);
}

main().catch((err) => {
  console.error("\n[ERROR]", err.message || err);
  process.exit(1);
});
