export const docContent: Record<string, { title: string; category: string; content: string }> = {
// DOCS
'overview': { title: 'Overview', category: 'Getting Started', content: `# Dashboard Overview\n\nWelcome to the Whale Alert Network Dashboard. This platform is designed for professional actors requiring zero-latency, cryptographically secure access to global on-chain telemetry.\n\n## The Zero-Trust Paradigm\nUnlike traditional analytics platforms, the Dashboard operates on a zero-trust architecture. We do not store your IP, we do not require email addresses, and we do not log your queries in plaintext. Your data is secured via AES-GCM encryption and ephemeral keys.\n\n## Core Capabilities\n* **Real-Time Data:** Intercept capital flows before they hit block finality.\n* **Entity Resolution:** Unmask multi-hop transactions across L1 and L2 networks.\n* **Encrypted Comms:** Engage in E2EE discussions via the Whale Chat.` },
'quickstart': { title: 'Quickstart', category: 'Getting Started', content: `# Quickstart (3 Minutes)\n\nInitialize your session and execute your first query.\n\n## 1. Cryptographic Handshake\nNavigate to the Connect portal. If you are on a PC, use your mobile device to scan the QR code. The mobile device will perform a ZK-liveness check and sign an ephemeral payload to unlock your PC session automatically.\n\n## 2. Global Mempool Access\nOnce authenticated, navigate to the Dashboard. The platform will automatically synchronize with the active memory graph, displaying the global liquidity heatmap.\n\n## 3. First API Request\nGenerate an API key in your Settings panel and execute a test query:\n\`\`\`bash\ncurl -H "x-api-key: $WHALE_KEY" https://api.whalealert.com/v3/telemetry/ping\n\`\`\`` },
'core-concepts': { title: 'Core Concepts', category: 'Getting Started', content: `# Core Concepts\n\nUnderstanding the fundamental primitives of the Whale Alert Network.\n\n## Kinetic Analysis\nWe define "Kinetic Analysis" as the real-time measurement of capital acceleration. Instead of looking at static balances, our engine calculates the *velocity* and *directionality* of funds moving out of cold storage.\n\n## OTC Proximity\nTransactions that interact with known OTC (Over-The-Counter) desks are flagged with a Proximity score, indicating hidden professional accumulation.` },
'whale-code': { title: 'Whale Code', category: 'Getting Started', content: `# Whale Code\n\nWhale Code is our proprietary Domain-Specific Language (DSL) for programming autonomous agents.\n\n**Redirecting...** Please refer to the dedicated Whale Code repository for advanced scripting tutorials.` },

'platform/architecture': { title: 'Architecture', category: 'Platform', content: `# Architecture Deep-Dive\n\nThe Network infrastructure is designed for absolute deterministic reliability and zero-latency execution across both PC and Mobile environments.\n\n## The PC Desktop Interface\nThe desktop environment is protected by a multi-layered middleware. \n1. **Session Hydration:** The account hook asynchronously validates the JWT cookie.\n2. **Fail-Closed Rendering:** If the session is invalid, the dashboard unmounts completely, preventing any UI leaks.\n3. **Biometric Gate:** Unauthenticated users are presented with the biometric gate, establishing a WebSocket polling connection waiting for the mobile payload.\n\n## The Mobile Biometric Engine\nThe mobile application acts as the cryptographic key.\n1. **Optical Ingestion:** Scanning the ephemeral session ID.\n2. **Ultrasonic Liveness:** A highly sensitive algorithm detects human blinks.\n3. **Payload Construction:** The proof is encrypted and transmitted to the relay server.\n\n## Atomic Synchronization\nOnce the mobile payload hits the verification endpoint, the PC application detects the success state, mints the final JWT, and automatically unlocks the dashboard.` },
'platform/authentication': { title: 'Authentication (SIWE)', category: 'Platform', content: `# Sign-In With Ethereum & ZK Liveness\n\nAuthentication on the Network is strictly cryptographic. We do not use passwords.\n\n## The EIP-4361 Standard\nSign-In with Ethereum (SIWE) provides a secure, standard way to authenticate.\n1. The server generates a single-use \`Nonce\`.\n2. The client signs a standard message containing the \`Nonce\`, \`Domain\`, and \`URI\`.\n3. The server verifies the ECDSA signature against the provided \`Address\`.\n\n## Biometric Liveness\nFor professional access, the dashboard requires a 3D Liveness attestation. This ensures the operator is biologically present.` },
'platform/neo4j': { title: 'Network Ledger', category: 'Platform', content: `# Network Ledger\n\nOur backend utilizes a distributed graph database to map multi-dimensional capital flows.\n\n## Graph Resolution\nStandard relational databases fail at tracing multi-hop transactions. Our graph resolves entities up to 6 hops deep in under 40 milliseconds, clustering disparate wallets into unified "Professional Entities".` },
'platform/smart-contracts': { title: 'Smart Contracts', category: 'Platform', content: `# Smart Contracts\n\nThe protocol relies on a suite of immutable contracts deployed on Ethereum Mainnet.\n\n## Core Contracts\n* **Registry:** Maintains the public keys of verified operators.\n* **Subscription:** Handles automated USDC/USDT fee deductions for API access.\n* **Nullifier:** Prevents replay attacks on biometric attestations.` },
'platform/node-deployment': { title: 'Node Deployment', category: 'Platform', content: `# Edge Node Deployment\n\nProfessional clients can deploy localized Edge Nodes to reduce latency to the ledger.\n\nBy deploying an Edge Node in your proprietary VPC (AWS/GCP), you eliminate public internet routing for API requests, dropping round-trip telemetry times to < 2ms.` },
'platform/websocket-streams': { title: 'WebSocket Streams', category: 'Platform', content: `# Sub-Millisecond WebSocket Streams\n\nThe primary ingestion method for quantitative funds.\n\nOur WebSockets push raw mempool data encoded in lightweight Protobufs. This bypasses HTTP overhead, allowing trading algorithms to front-run movements.` },
'platform/whale-chat': { title: 'Whale Chat Forum', category: 'Platform', content: `# Whale Chat Forum\n\nThe definitive communication protocol for verified accounts.\n\n## E2EE Architecture\nThe Whale Chat uses the XMTP (Extensible Message Transport Protocol) to establish End-to-End Encrypted (E2EE) tunnels between wallets. This guarantees that your messages cannot be intercepted.\n\n## Instant Access\nFor instant access, the platform deploys a floating action button. Once KYC is finalized, this sterile, minimalist interface injects directly into your dashboard, allowing unblockable P2P comms.\n\n## Professional Forums\nEngage in discussions, share heuristic models, and coordinate liquidity strategies without fear of surveillance.` },

'integrations/walletconnect': { title: 'WalletConnect v2', category: 'Integrations', content: `# WalletConnect v2 Integration\n\nFull support for the WalletConnect v2 protocol, enabling seamless bridging between cold storage hardware (Ledger, Trezor) and the Dashboard.` },
'integrations/tron': { title: 'Tron / TRC-20', category: 'Integrations', content: `# Tron Network (TRC-20) Support\n\nThe dashboard natively supports TRC-20 USDT tracking, a critical vector for monitoring OTC desk settlements.` },
'integrations/getblock': { title: 'GetBlock RPC', category: 'Integrations', content: `# GetBlock RPC Infrastructure\n\nOur primary fallback RPC provider, ensuring 99.999% uptime for mempool ingestion across 50+ chains.` },
'integrations/resend': { title: 'Resend Email', category: 'Integrations', content: `# Email Alerts via Resend\n\nConfigure highly customizable, beautifully formatted email alerts for specific kinetic heuristics using our Resend integration.` },
'integrations/prisma': { title: 'Prisma ORM', category: 'Integrations', content: `# Prisma Relational Layer\n\nWhile the graph database handles relationships, Prisma manages user metadata, API keys, and subscription tiers using connection-pooled PostgreSQL clusters.` },

// DEVELOPER
'developer/overview': { title: 'Developer Overview', category: 'Getting Started', content: `# Developer Overview\n\nWelcome to the API. Our infrastructure provides programmatic access to sophisticated on-chain data.\n\n## Access Tiers\n* **Standard**: REST access, 60 requests/min.\n* **Pro**: REST + WebSocket access, 300 requests/min.\n* **Professional**: Dedicated Kafka streams, infinite limits.\n\nNavigate to your Dashboard > Settings to generate your API keys.` },
'developer/auth': { title: 'Authentication', category: 'Getting Started', content: `# API Authentication\n\nAll API requests must include your API Key in the headers.\n\n\`\`\`json\n{\n  "x-api-key": "wh_live_a1b2c3d4e5f6g7h8i9j0"\n}\n\`\`\`\n\nDo not expose your API keys in client-side code. Route all requests through your proprietary backend.` },
'developer/api-keys': { title: 'API Keys', category: 'Getting Started', content: `# Managing API Keys\n\nAPI keys can be generated, rotated, and revoked from the Security Panel.\n\n## Key Scopes\nYou can restrict API keys to specific endpoints (e.g., Read-Only Market Data vs. Write-Access Trading Execution) to mitigate damage in the event of a leak.` },
'developer/rate-limits': { title: 'Rate Limits', category: 'Getting Started', content: `# Rate Limits & WAF Engine\n\nOur Web Application Firewall (WAF) enforces strict rate limiting.\n\n## The WAF Engine\nUsing a distributed Redis cluster, the WAF tracks requests via IP and API Key. Exceeding limits triggers a \`429 Too Many Requests\` response.\n\nIf you trigger the WAF threshold 5 times in an hour, your IP will be temporarily blacklisted. Use exponential backoff in your integration.` },

'developer/rest/overview': { title: 'Reference Overview', category: 'REST API', content: `# REST API V3\n\nThe primary interface for historical queries, state fetching, and configuration.\n\n## Base URL\n\`https://api.whalealert.com/v3\`\n\nAll endpoints return responses in standard JSON format, adhering to the JSend specification.` },
'developer/rest/whale-alerts': { title: 'Whale Alerts', category: 'REST API', content: `# Whale Alerts API\n\nQuery high-volume transactional data.\n\n## GET /alerts/kinetic\n\`\`\`json\n{\n  "status": "success",\n  "data": {\n    "alerts": [\n      {\n        "id": "tx_987654321",\n        "chain": "ETH",\n        "asset": "USDC",\n        "amount_usd": 154000000,\n        "sender_entity": "Unknown Pool",\n        "recipient_entity": "Binance Cold Storage",\n        "kinetic_velocity": 0.94,\n        "timestamp": "2026-05-14T21:45:00Z"\n      }\n    ]\n  }\n}\n\`\`\`` },
'developer/rest/market-data': { title: 'Market Data', category: 'REST API', content: `# Market Data API\n\nRetrieve global liquidity metrics.\n\n## GET /market/global\n\`\`\`json\n{\n  "status": "success",\n  "data": {\n    "total_market_cap_usd": 2840000000000,\n    "btc_dominance": 52.4,\n    "eth_gas_gwei": 14.2,\n    "professional_inflow_24h": 4500000000\n  }\n}\n\`\`\`` },
'developer/rest/wallets': { title: 'Wallets & Entities', category: 'REST API', content: `# Entity Resolution API\n\nResolve an address into a known professional entity.\n\n## GET /entities/{address}\n\`\`\`json\n{\n  "status": "success",\n  "data": {\n    "address": "0x...",\n    "resolved_name": "Wintermute Trading",\n    "confidence_score": 0.99,\n    "tags": ["Market Maker", "High Frequency"],\n    "estimated_portfolio_usd": 850000000\n  }\n}\n\`\`\`` },
'developer/rest/forum': { title: 'Forum Posts', category: 'REST API', content: `# Forum API\n\nProgrammatic access to Whale Chat public feeds.\n\n## GET /forum/feed\nRetrieve the latest heuristic models posted by verified entities.` },
'developer/rest/subscriptions': { title: 'Subscriptions', category: 'REST API', content: `# Subscriptions API\n\nManage your API billing and tier allocation programmatically.` },
'developer/rest/transactions': { title: 'Transactions', category: 'REST API', content: `# Transactions API\n\nQuery raw, undecoded transaction traces directly from the archive nodes.` },

'developer/ws/connection': { title: 'Connection', category: 'WebSocket API', content: `# WebSocket Connection\n\nEstablish a persistent stream.\n\n## Handshake\n\`wss://stream.whalealert.com/v3/connect?key=YOUR_API_KEY\`\n\nThe server will respond with an \`AUTH_SUCCESS\` opcode.` },
'developer/ws/channels': { title: 'Channels', category: 'WebSocket API', content: `# Channels\n\nMultiplex multiple data streams over a single connection.\n\n## Subscribe Payload\n\`\`\`json\n{\n  "op": "SUBSCRIBE",\n  "channels": ["mempool_eth", "darkpool_flows"],\n  "filters": {\n    "min_usd_value": 1000000\n  }\n}\n\`\`\`` },
'developer/ws/events': { title: 'Events', category: 'WebSocket API', content: `# Event Schemas\n\n## MEMPOOL_TX Event\n\`\`\`json\n{\n  "event": "MEMPOOL_TX",\n  "data": {\n    "hash": "0x...",\n    "from": "0x...",\n    "to": "0x...",\n    "value": "1000000000000000000000",\n    "gas_price": "15000000000"\n  }\n}\n\`\`\`` },

'developer/sdk/typescript': { title: 'TypeScript SDK', category: 'SDKs', content: `# TypeScript SDK\n\n\`\`\`bash\nnpm install @whalealert/sdk\n\`\`\`\n\n\`\`\`typescript\nimport { WhaleClient } from '@whalealert/sdk';\nconst client = new WhaleClient({ apiKey: 'wh_...' });\nconst entity = await client.entities.resolve('0x...');\n\`\`\`` },
'developer/sdk/python': { title: 'Python SDK', category: 'SDKs', content: `# Python SDK\n\n\`\`\`bash\npip install whalealert-sdk\n\`\`\`\n\n\`\`\`python\nfrom whalealert import WhaleClient\nclient = WhaleClient(api_key='wh_...')\nentity = client.entities.resolve('0x...')\n\`\`\`` },
'developer/sdk/webhooks': { title: 'Webhook Guide', category: 'SDKs', content: `# Webhook Integration\n\nReceive POST requests to your servers when specific heuristics are met. Verify the payload using the \`x-signature\` HMAC header.` },
'developer/sdk/changelog': { title: 'Changelog', category: 'SDKs', content: `# SDK Changelog\n\n## v3.0.0\n- Introduced Graph queries.\n- Added XMTP Whale Chat messaging functions.` },

// OPERATOR
'operator/overview': { title: 'Operator Overview', category: 'Getting Started', content: `# Node Operator Infrastructure\n\nBecome a foundational pillar of the Network by deploying a full indexing node.\n\n## Why Operate?\nNode operators receive programmatic yield generated by the network's API fees, proportional to their uptime and verified data integrity.` },
'operator/prerequisites': { title: 'Prerequisites', category: 'Getting Started', content: `# Hardware Requirements\n\nRunning a Node requires professional-grade hardware.\n\n## Minimum Specifications\n* **CPU**: 8 Cores\n* **RAM**: 32 GB ECC\n* **Storage**: 2 TB NVMe Gen4 SSD\n* **Network**: 1 Gbps Symmetric Fiber` },

'operator/setup/node': { title: 'Running a Full Node', category: 'Setup', content: `# Deploying a Full Node\n\n\`\`\`bash\ngit clone https://github.com/whalealert/node.git\ncd node\ndocker compose -f docker-compose.prod.yml up -d\n\`\`\`` },
'operator/setup/sequencer': { title: 'Running a Sequencer', category: 'Setup', content: `# Sequencer Setup\n\nSequencers order transactions in our L2 architecture. This requires a dedicated bare-metal server with <1ms latency to Ethereum RPC endpoints.` },
'operator/setup/prover': { title: 'Running a Prover', category: 'Setup', content: `# ZK Prover Setup\n\nProvers require massive GPU compute (e.g., A100s) to generate proofs for the network state.` },
'operator/setup/source': { title: 'Building from Source', category: 'Setup', content: `# Compiling the Rust Node\n\n\`\`\`bash\ncargo build --release\n./target/release/node --config config.toml\n\`\`\`` },
'operator/setup/snapshots': { title: 'Snapshots & Syncing', category: 'Setup', content: `# Fast Sync via Snapshots\n\nDownload the latest snapshot from our S3 buckets to reduce sync time from 72 hours to 4 hours.` },

'operator/operation/monitoring': { title: 'Monitoring', category: 'Operation', content: `# Telemetry & Monitoring\n\nMaintain a 99.99% uptime to avoid slashing. Every node instance ships with a pre-configured Grafana dashboard accessible at port \`3030\`.` },
'operator/operation/keystore': { title: 'Keystore Management', category: 'Operation', content: `# Keystore Security\n\nStore your node's validator keys in an encrypted JSON keystore. Never expose the password in plaintext scripts.` },
'operator/operation/sequencer': { title: 'Sequencer Management', category: 'Operation', content: `# Sequencer Management\n\nMonitor the mempool backlog and adjust gas limits dynamically to ensure constant block production.` },
'operator/operation/faq': { title: 'FAQs & Common Issues', category: 'Operation', content: `# Operator FAQs\n\n**Q: Why is my node falling behind?**\nA: Your IOPS are too low. Ensure you are using NVMe Gen4 drives in RAID 0.` },

'operator/reference/cli': { title: 'CLI Reference', category: 'Reference', content: `# Node CLI Commands\n\n\`node status\`\n\`node keys import\`\n\`node db compact\`` },
'operator/reference/rpc': { title: 'Node JSON RPC API', category: 'Reference', content: `# Local RPC API\n\nQuery your local node directly on port \`8545\` using standard Ethereum JSON-RPC calls.` },
'operator/reference/changelog': { title: 'Changelog', category: 'Reference', content: `# Node Client Changelog\n\n## v2.4.1\n- Optimized bulk ingestion.\n- Fixed memory leak in peer discovery.` },
'operator/reference/glossary': { title: 'Glossary', category: 'Reference', content: `# Operator Glossary\n\n* **Epoch:** A 32-block timeframe.\n* **Slashing:** The destruction of staked tokens due to node misbehavior.` },

// LEGAL
'legal/terms-of-service': { title: 'Terms of Service', category: 'Legal', content: `# Terms of Service\n\n**Last Updated:** May 2026\n\nWelcome to the Whale Alert Network ("Platform"). By accessing or using the Platform, you agree to be bound by these Terms of Service.\n\n## 1. Professional Access\nAccess to the dashboard is granted strictly to verified entities. You are responsible for maintaining the confidentiality of your session credentials.\n\n## 2. API Usage & Rate Limiting\nAPI access is governed by your subscription tier. The Platform reserves the right to throttle or suspend access if usage exceeds the automated limits defined in the Developer Overview.\n\n## 3. Data Integrity\nWhile we employ advanced cryptographic primitives to ensure data fidelity, on-chain telemetry is provided "as is". We make no warranties regarding the absolute completeness of liquidity feeds.\n\n## 4. Node Operations\nOperators participating in the decentralized network must adhere to the hardware and uptime requirements specified in the Operator documentation. Malicious behavior will result in stake slashing.` },
'legal/privacy-policy': { title: 'Privacy Policy', category: 'Legal', content: `# Privacy Policy\n\n**Last Updated:** May 2026\n\nWhale Alert Network respects the privacy of our professional clients. This policy outlines our data handling practices.\n\n## Zero-Knowledge Architecture\nThe Platform operates on a principle of absolute data minimization.\n\n* **Identity:** We do not store email addresses or personal identifiers unless explicitly provided for billing. Authentication is handled entirely via ECDSA signatures.\n* **Telemetry:** Your private queries, Watchlist configurations, and Hub filters are encrypted client-side. The protocol cannot decipher your surveillance targets.\n\n## Data Retention\nNode operator IP addresses and telemetry metrics are retained for 14 days solely for network health diagnostics, after which they are permanently purged from the active cache.` },
'legal/cookie-policy': { title: 'Cookie Policy', category: 'Legal', content: `# Cookie Policy\n\nThe Whale Alert Platform uses cookies exclusively for secure session management and essential functionality.\n\n## Essential Cookies\n* \`session\`: An encrypted JWT that maintains your authenticated session across the dashboard.\n* \`theme_preference\`: Stores your dark/light mode UI configuration.\n\n## Third-Party Tracking\nWe **do not** use third-party analytics, marketing trackers, or cross-site tracking pixels. Your activity remains entirely isolated within the Platform.` },
'legal/risk-disclosure': { title: 'Risk Disclosure', category: 'Legal', content: `# Risk Disclosure\n\n**WARNING: High-Volatility Environments**\n\nThe tools provided by the Whale Alert Network are designed for professional actors analyzing on-chain dynamics.\n\n## 1. Protocol Risks\nInteracting with decentralized networks involves inherent smart contract and consensus risks.\n\n## 2. Signal Validity\nHeuristic signals are predictive models based on historical blockchain state. They do not constitute financial advice and are susceptible to manipulation by highly capitalized actors via wash-trading.` },
'legal/whale-code': { title: 'Whale Code Legal', category: 'Legal', content: `# Whale Code Licensing\n\nWhale Code is proprietary intellectual property of Whale Alert Network. Enterprise licenses restrict the redistribution of autonomous agents built using our internal DSL.` },
'legal/whitepaper': { title: 'Whitepaper', category: 'Legal', content: `# Professional Whitepaper\n\nThe foundational document detailing the mathematics behind the Kinetic Analysis Engine and the Graph resolution models.\n\n[Download PDF (v3.1)](#)` }
};
