/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as endgame from "./endgame";
export type { endgame };
import type * as governance from "./governance";
export type { governance };
import type * as tokenomics from "./tokenomics";
export type { tokenomics };
